# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build/Test JDK 21

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: |
            dbus-java-core/pom.xml
            dbus-java-examples/pom.xml
            dbus-java-osgi/pom.xml
            dbus-java-tests/pom.xml
            dbus-java-transport-jnr-unixsocket/pom.xml
            dbus-java-transport-junixsocket/pom.xml
            dbus-java-transport-native-unixsocket/pom.xml
            dbus-java-transport-tcp/pom.xml
            dbus-java-utils/pom.xml
    - name: Build with Maven
      run: |
        dbus-daemon --session --fork --address unix:path=/tmp/dbustest,guid=$(echo $RANDOM | md5sum | cut -d ' ' -f 1)
        export DBUS_SESSION_BUS_ADDRESS=unix:path=/tmp/dbustest 
        mvn -B package --file pom.xml -P sonarcloud-with-tests
