name: Test - SonarCloud Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        cache-dependency-path: |
            dbus-java-core/pom.xml
            dbus-java-examples/pom.xml
            dbus-java-osgi/pom.xml
            dbus-java-tests/pom.xml
            dbus-java-transport-jnr-unixsocket/pom.xml
            dbus-java-transport-junixsocket/pom.xml
            dbus-java-transport-native-unixsocket/pom.xml
            dbus-java-transport-tcp/pom.xml
            dbus-java-utils/pom.xml
      - name: SonarCloud Scan
        run: mvn -B clean verify -Psonarcloud -Dsonar.login=${{ secrets.SONAR_TOKEN }}
